[tool.poetry]
name = "recipe-book-backend"
version = "0.1.0"
description = "Recipe Book"
authors = ["Mansur Gabidullin <mansur.gabidullin@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "recipe_book" }]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.prod.dependencies]
python-dotenv = "^0.21.1"
pydantic = "^1.10.4"
fastapi = "^0.89.1"
asyncpg = "^0.27.0"
sqlalchemy = "^2.0.2"
uvicorn = "^0.20.0"
gunicorn = "^20.1.0"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
pylint = "^2.16.1"
mypy = "^1.0.0"
pre-commit = "^3.0.4"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"
pytest-randomly = "^3.12.0"
pytest-cov = "^4.0.0"
pytest-asyncio = "^0.20.3"

[tool.poetry.scripts]
create_env = "recipe_book:create_env"
init_db = "recipe_book:init_db"
start = "recipe_book:start"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v -vv -ra -q --strict-markers --no-cov-on-fail --cov-config=.coveragerc --cov-report html --cov-report term --cov=recipe_book"
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]
pythonpath = ["recipe_book"]
testpaths = ["recipe_book/tests"]

[tool.pylint.master]
init-hook = 'import sys; sys.path.append("recipe_book")'

[tool.pylint.format]
max-line-length = 120

[tool.mypy]
python_version = "3.11"
mypy_path = ["recipe_book"]
files = ["recipe_book"]
strict = true
ignore_missing_imports = true

[tool.black]
target-version = ['py311']
line-length = 120
include = '\.pyi?$'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
