[tool.poetry]
name = "recipe-book-backend"
version = "0.1.0"
description = "Recipe Book"
authors = ["Mansur Gabidullin <mansur.gabidullin@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "recipe_book" }]

[tool.poetry.dependencies]
python = "^3.11"
gunicorn = "^20.1.0"
pydantic = "^1.10.4"
fastapi = "^0.89.1"
asyncpg = "^0.27.0"
python-dotenv = "^0.21.1"
sqlalchemy = "^2.0.1"
uvicorn = "^0.20.0"

[tool.poetry.scripts]
create_env = "recipe_book:create_env"
init_db = "recipe_book:init_db"
start = "recipe_book:start"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
