from typing import Final

USER_LOGIN_MIN_LENGTH: Final = 5
USER_LOGIN_MAX_LENGTH: Final = 255

USER_PASSWORD_MIN_LENGTH: Final = 5

USER_NAME_MIN_LENGTH: Final = 5
USER_NAME_MAX_LENGTH: Final = 255

USER_EMAIL_MAX_LENGTH: Final = 254

USER_PHONE_NUMBER_MIN_LENGTH: Final = 16
USER_PHONE_NUMBER_MAX_LENGTH: Final = 16

USER_SURNAME_MIN_LENGTH: Final = 5
USER_SURNAME_MAX_LENGTH: Final = 255

USER_PATRONYMIC_MIN_LENGTH: Final = 5
USER_PATRONYMIC_MAX_LENGTH: Final = 255

USER_NICKNAME_MIN_LENGTH: Final = 5
USER_NICKNAME_MAX_LENGTH: Final = 255

GROUP_NAME_MAX_LENGTH: Final = 255

ROLE_NAME_MAX_LENGTH: Final = 255

PERMISSION_NAME_MAX_LENGTH: Final = 255
