version: '3.9'
services:

    # PostgresQL Service
    postgres:
        image: postgres:15.4-alpine3.18
        container_name: recipe-book-postgres
        hostname: recipe-book-postgres
        restart: unless-stopped
        tty: true
        ports:
            - "${DB_PORT:-5432}:5432"
        environment:
            - PGDATA=${DB_DATA_PATH:-/var/lib/postgresql/data}
            - POSTGRES_DB=${DB_NAME:-postgres}
            - POSTGRES_USER=${DB_USER:-postgres}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./data:${DB_DATA_PATH:-/var/lib/postgresql/data}
        networks:
            - recipe-book-network

# Docker Networks
networks:
    recipe-book-network:
        driver: bridge
