version: '3.9'
services:

    # PostgresQL Service
    postgres:
        image: postgres:15.1-alpine3.17
        container_name: recipe-book-postgres
        hostname: recipe-book-postgres
        restart: unless-stopped
        tty: true
        ports:
            - "${DB_PORT}:5432"
        environment:
            - PGDATA=${DB_DATA_PATH}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./data:${DB_DATA_PATH}
        networks:
            - recipe-book-network

# Docker Networks
networks:
    recipe-book-network:
        driver: bridge